; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Fri Jun 19 2020 19:54:19 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform

G30 P0 X20 Y150 Z-9999       ; Probe near left z-screw
G30 P1 X300 Y150 Z-9999 S2   ; Probe near right z-screw

G29                          ; probe the bed and enable compensation


