; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Fri Jun 19 2020 19:54:19 GMT-0700 (Pacific Daylight Time)

G91
;G1 H1 Z-350 F1000        ; Move up quickly
G1 H1 Z10 F500          ; Move back down again.
G90
M401
; Home Z
G30
M402