; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Fri Jun 19 2020 19:54:19 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

